import { NgModule } from "@angular/core";
import {
  MatButtonModule,
  MatCheckboxModule,
  MatNativeDateModule,
  MatSelectModule,
  MatCardModule,
  MatExpansionModule,
  MatDividerModule,
  MatIconModule,
  MatFormFieldModule,
  MatInputModule,
  MatDatepickerModule,
  MatToolbarModule,
  MatMenuModule,
  MatGridListModule,
  MatSlideToggleModule,
  MatDialogModule,
  MatTabsModule,
  MatListModule,
  MatTooltipModule,
  MatProgressSpinnerModule,
  MatButtonToggleModule,
  MatSnackBarModule
} from "@angular/material";

@NgModule({
  imports: [
    MatButtonModule,
    MatCheckboxModule,
    MatNativeDateModule,
    MatSelectModule,
    MatCardModule,
    MatExpansionModule,
    MatDividerModule,
    MatIconModule,
    MatFormFieldModule,
    MatInputModule,
    MatDatepickerModule,
    MatToolbarModule,
    MatMenuModule,
    MatGridListModule,
    MatSlideToggleModule,
    MatDialogModule,
    MatTabsModule,
    MatListModule,
    MatTooltipModule,
    MatProgressSpinnerModule,
    MatButtonToggleModule,
    MatSnackBarModule
  ],
  exports: [
    MatButtonModule,
    MatCheckboxModule,
    MatNativeDateModule,
    MatSelectModule,
    MatCardModule,
    MatExpansionModule,
    MatDividerModule,
    MatIconModule,
    MatFormFieldModule,
    MatInputModule,
    MatDatepickerModule,
    MatToolbarModule,
    MatMenuModule,
    MatGridListModule,
    MatSlideToggleModule,
    MatDialogModule,
    MatTabsModule,
    MatListModule,
    MatTooltipModule,
    MatProgressSpinnerModule,
    MatButtonToggleModule,
    MatSnackBarModule
  ]
})
export class Material {}
